### ISSUE TITLE
Compile Errors (Ubuntu 14.04)?

### ISSUE THREAD

**Issue by bmeynell** [Big-Data-Manning/big-data-code#4]
Java noob here. Trying to compile and use Pail examples from Big Data book on Ubuntu 14.04. Below is the full output. Any and all help greatly appreciated! I'll continue to try and figure out. @handdola @nagarajanchinnasamy - kindly lend a hand? Cheers. 

```
/home/bmeynell/big-data-code (master)$ ls
genthrift.sh  pom.xml  README.md  src  target
```

```
/home/bmeynell/big-data-code (master)$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

```
/home/bmeynell/big-data-code (master)$ mvn -version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-57-generic", arch: "amd64", family: "unix"
```

```
/home/bmeynell/big-data-code (master)$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

```
/home/bmeynell/big-data-code (master)$ mvn compile
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building big-data-book 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ big-data-book ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/bmeynell/big-data-code/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ big-data-book ---
[INFO] Compiling 27 source files to /home/bmeynell/big-data-code/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.439s
[INFO] Finished at: Sun Oct 02 00:19:49 UTC 2016
[INFO] Final Memory: 14M/202M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project big-data-book: Compilation failure: Compilation failure:
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[36,1] error: annotations are not supported in -source 1.3
[ERROR]
[ERROR] (use -source 5 or higher to enable annotations)
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[38,66] error: generics are not supported in -source 1.3
[ERROR]
[ERROR] (use -source 5 or higher to enable generics)
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[50,21] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[50,63] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[56,25] error: for-each loops are not supported in -source 1.3
[ERROR]
[ERROR] (use -source 5 or higher to enable for-each loops)
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[91,4] error: invalid method declaration; return type required
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[104,22] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[105,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[106,146] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[107,15] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[108,66] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[108,86] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[108,104] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[111,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[117,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[120,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[122,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[125,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[128,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[133,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[137,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[140,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[143,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[148,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[151,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[154,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[156,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[157,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[159,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[163,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[164,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[167,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[170,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[171,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[174,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[177,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[181,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[182,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[184,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[186,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[188,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[190,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[192,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[194,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[197,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[199,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[201,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[202,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[203,2] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[205,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[213,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[215,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[221,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[223,4] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/ExternalDataSystem.java:[282,0] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[36,1] error: annotations are not supported in -source 1.3
[ERROR]
[ERROR] (use -source 5 or higher to enable annotations)
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[38,56] error: generics are not supported in -source 1.3
[ERROR]
[ERROR] (use -source 5 or higher to enable generics)
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[56,21] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[56,63] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,4] error: invalid method declaration; return type required
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,20] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,21] error: ')' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,26] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,27] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,28] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,29] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,47] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,48] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[57,49] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,10] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,11] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,12] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,17] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,18] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,20] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,29] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,30] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[62,31] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,10] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,11] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,12] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,17] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,18] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,20] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,29] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,30] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[63,31] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[68,25] error: for-each loops are not supported in -source 1.3
[ERROR]
[ERROR] (use -source 5 or higher to enable for-each loops)
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[109,4] error: invalid method declaration; return type required
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[124,23] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[125,10] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[126,22] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[127,9] error: class or interface expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[128,146] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[129,14] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[129,38] error: <identifier> expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[129,40] error: illegal start of type
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[129,43] error: ')' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[129,47] error: ';' expected
[ERROR]
[ERROR] /home/bmeynell/big-data-code/src/java/manning/schema/Pedigree.java:[129,85] error: <identifier> expected
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by bmeynell** [comment]
I think I was able to resolve this by modifying `pom.xml` as so:

``` diff
$ git diff
diff --git a/pom.xml b/pom.xml
index 0208f90..a13bf69 100644
--- a/pom.xml
+++ b/pom.xml
@@ -21,6 +21,14 @@
     </testResources>
   <plugins>
     <plugin>
+        <artifactId>maven-compiler-plugin</artifactId>
+        <version>3.2</version>
+        <configuration>
+            <source>1.7</source>
+            <target>1.7</target>
+        </configuration>
+    </plugin>
+    <plugin>
       <groupId>com.theoryinpractise</groupId>
       <artifactId>clojure-maven-plugin</artifactId>
       <version>1.3.10</version>
```

Then ran `mvn compile`:

```
$ mvn compile
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building big-data-book 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ big-data-book ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/bmeynell/big-data-code/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ big-data-book ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 27 source files to /home/bmeynell/big-data-code/target/classes
[INFO] /home/bmeynell/big-data-code/src/java/manning/batchlayer/BatchWorkflow.java: /home/bmeynell/big-data-code/src/java/manning/batchlayer/BatchWorkflow.java uses or overrides a deprecated API.
[INFO] /home/bmeynell/big-data-code/src/java/manning/batchlayer/BatchWorkflow.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/bmeynell/big-data-code/src/java/manning/speedlayer/UniquesOverTime.java: Some input files use unchecked or unsafe operations.
[INFO] /home/bmeynell/big-data-code/src/java/manning/speedlayer/UniquesOverTime.java: Recompile with -Xlint:unchecked for details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.970s
[INFO] Finished at: Mon Oct 03 23:49:40 UTC 2016
[INFO] Final Memory: 23M/205M
[INFO] ------------------------------------------------------------------------
```

And the compiled Java classes are there!

```
$ tree /home/bmeynell/big-data-code/target/classes
/home/bmeynell/big-data-code/target/classes
└── manning
    ├── batchlayer
    │   ├── BatchWorkflow$1.class
    │   ├── BatchWorkflow$AnalyzeVisits.class
    │   ├── BatchWorkflow$BidirectionalEdge.class
    │   ├── BatchWorkflow.class
    │   ├── BatchWorkflow$ConstructHyperLogLog.class
    │   ├── BatchWorkflow$Debug.class
    │   ├── BatchWorkflow$EdgifyEquiv.class
    │   ├── BatchWorkflow$EmitGranularities.class
    │   ├── BatchWorkflow$ExtractDomain.class
    │   ├── BatchWorkflow$ExtractPageViewFields.class
    │   ├── BatchWorkflow$IterateEdges.class
    │   ├── BatchWorkflow$MakeNormalizedPageview.class
    │   ├── BatchWorkflow$MergeHyperLogLog.class
    │   ├── BatchWorkflow$NormalizeURL.class
    │   ├── BatchWorkflow$ToHourBucket.class
    │   ├── BatchWorkflow$ToSerializedLong.class
    │   ├── BatchWorkflow$ToSerializedLongPair.class
    │   ├── BatchWorkflow$ToSerializedString.class
    │   ├── BatchWorkflow$ToUrlBucketedKey.class
    │   └── BatchWorkflow$UrlOnlyScheme.class
    ├── schema
    │   ├── Data$1.class
    │   ├── Data.class
    │   ├── Data$DataStandardScheme.class
    │   ├── Data$DataStandardSchemeFactory.class
    │   ├── Data$DataTupleScheme.class
    │   ├── Data$DataTupleSchemeFactory.class
    │   ├── Data$_Fields.class
    │   ├── DataUnit$1.class
    │   ├── DataUnit.class
    │   ├── DataUnit$_Fields.class
    │   ├── EquivEdge$1.class
    │   ├── EquivEdge.class
    │   ├── EquivEdge$EquivEdgeStandardScheme.class
    │   ├── EquivEdge$EquivEdgeStandardSchemeFactory.class
    │   ├── EquivEdge$EquivEdgeTupleScheme.class
    │   ├── EquivEdge$EquivEdgeTupleSchemeFactory.class
    │   ├── EquivEdge$_Fields.class
    │   ├── ExternalDataSystem$1.class
    │   ├── ExternalDataSystem.class
    │   ├── ExternalDataSystem$ExternalDataSystemStandardScheme.class
    │   ├── ExternalDataSystem$ExternalDataSystemStandardSchemeFactory.class
    │   ├── ExternalDataSystem$ExternalDataSystemTupleScheme.class
    │   ├── ExternalDataSystem$ExternalDataSystemTupleSchemeFactory.class
    │   ├── ExternalDataSystem$_Fields.class
    │   ├── GenderType.class
    │   ├── Location$1.class
    │   ├── Location.class
    │   ├── Location$_Fields.class
    │   ├── Location$LocationStandardScheme.class
    │   ├── Location$LocationStandardSchemeFactory.class
    │   ├── Location$LocationTupleScheme.class
    │   ├── Location$LocationTupleSchemeFactory.class
    │   ├── OrigSystem$1.class
    │   ├── OrigSystem.class
    │   ├── OrigSystem$_Fields.class
    │   ├── PageID$1.class
    │   ├── PageID.class
    │   ├── PageID$_Fields.class
    │   ├── PageProperty$1.class
    │   ├── PageProperty.class
    │   ├── PageProperty$_Fields.class
    │   ├── PageProperty$PagePropertyStandardScheme.class
    │   ├── PageProperty$PagePropertyStandardSchemeFactory.class
    │   ├── PageProperty$PagePropertyTupleScheme.class
    │   ├── PageProperty$PagePropertyTupleSchemeFactory.class
    │   ├── PagePropertyValue$1.class
    │   ├── PagePropertyValue.class
    │   ├── PagePropertyValue$_Fields.class
    │   ├── PageViewEdge$1.class
    │   ├── PageViewEdge.class
    │   ├── PageViewEdge$_Fields.class
    │   ├── PageViewEdge$PageViewEdgeStandardScheme.class
    │   ├── PageViewEdge$PageViewEdgeStandardSchemeFactory.class
    │   ├── PageViewEdge$PageViewEdgeTupleScheme.class
    │   ├── PageViewEdge$PageViewEdgeTupleSchemeFactory.class
    │   ├── PageViewSystem$1.class
    │   ├── PageViewSystem.class
    │   ├── PageViewSystem$_Fields.class
    │   ├── PageViewSystem$PageViewSystemStandardScheme.class
    │   ├── PageViewSystem$PageViewSystemStandardSchemeFactory.class
    │   ├── PageViewSystem$PageViewSystemTupleScheme.class
    │   ├── PageViewSystem$PageViewSystemTupleSchemeFactory.class
    │   ├── Pedigree$1.class
    │   ├── Pedigree.class
    │   ├── Pedigree$_Fields.class
    │   ├── Pedigree$PedigreeStandardScheme.class
    │   ├── Pedigree$PedigreeStandardSchemeFactory.class
    │   ├── Pedigree$PedigreeTupleScheme.class
    │   ├── Pedigree$PedigreeTupleSchemeFactory.class
    │   ├── PersonID$1.class
    │   ├── PersonID.class
    │   ├── PersonID$_Fields.class
    │   ├── PersonProperty$1.class
    │   ├── PersonProperty.class
    │   ├── PersonProperty$_Fields.class
    │   ├── PersonProperty$PersonPropertyStandardScheme.class
    │   ├── PersonProperty$PersonPropertyStandardSchemeFactory.class
    │   ├── PersonProperty$PersonPropertyTupleScheme.class
    │   ├── PersonProperty$PersonPropertyTupleSchemeFactory.class
    │   ├── PersonPropertyValue$1.class
    │   ├── PersonPropertyValue.class
    │   ├── PersonPropertyValue$_Fields.class
    │   └── Source.class
    ├── speedlayer
    │   ├── CassandraState$1.class
    │   ├── CassandraState$CassandraSerializerFactory.class
    │   ├── CassandraState.class
    │   ├── CassandraState$Factory.class
    │   ├── CassandraState$IntegerSerializer.class
    │   ├── CassandraState$Options.class
    │   ├── CassandraState$StringSerializer.class
    │   ├── TridentSpeedLayer$AnalyzeVisits$1.class
    │   ├── TridentSpeedLayer$AnalyzeVisits.class
    │   ├── TridentSpeedLayer$BooleanToInt.class
    │   ├── TridentSpeedLayer.class
    │   ├── TridentSpeedLayer$CombinedCombinerAggregator.class
    │   ├── TridentSpeedLayer$ExtractDomain.class
    │   ├── TridentSpeedLayer$NormalizeURL.class
    │   ├── TridentSpeedLayer$ToHourBucket.class
    │   ├── TridentSpeedLayer$Visit.class
    │   ├── TridentSpeedLayer$VisitInfo.class
    │   ├── UniquesOverTime.class
    │   ├── UniquesOverTime$ExtractFilterBolt.class
    │   ├── UniquesOverTime$PageviewScheme.class
    │   └── UniquesOverTime$UpdateCassandraBolt.class
    ├── tap
    │   ├── DataPailStructure.class
    │   ├── DataPailTap.class
    │   ├── DataPailTap$DataPailTapOptions.class
    │   ├── SplitDataPailStructure.class
    │   ├── SplitDataPailStructure$EdgeStructure.class
    │   ├── SplitDataPailStructure$FieldStructure.class
    │   ├── SplitDataPailStructure$PropertyStructure.class
    │   ├── SplitDataPailTap.class
    │   ├── SplitDataPailTap$SplitDataPailTapOptions.class
    │   └── ThriftPailStructure.class
    └── test
        └── Data.class

6 directories, 135 files
```

**Comment by bmeynell** [comment]
Similar success running `mvn package`, which creates a `/home/bmeynell/big-data-code/target/big-data-book-1.0.0-SNAPSHOT.jar`. However when attempting to run the jar file, it fails:

```
$ java -jar /home/bmeynell/big-data-code/target/big-data-book-1.0.0-SNAPSHOT.jar
no main manifest attribute, in /home/bmeynell/big-data-code/target/big-data-book-1.0.0-SNAPSHOT.jar
```

Have to run now. If anyone can lend a hand that'd be great, otherwise I'll keep investigating as I can squeeze in time.

**Comment by carlbastos** [comment]
On this same boat here - the difference is that I added `maven-jar-plugin` to `pom.xml` in order to try to circumvent the manifest error - since I am not sure what is the main Class name for the manifest, I tried `manning.batchlayer.BatchWorkflow` (big shot in the dark here):

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        ...
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <mainClass>manning.batchlayer.BatchWorkflow</mainClass>
            </manifest>
          </archive>
        </configuration>
        ...
      </plugin>
```

which gave me the following error after compiling and generating the package:

```
$ java -jar ~/big-data-code/target/big-data-book-1.0.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: backtype/hadoop/pail/PailStructure
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
    at java.lang.Class.getMethod0(Class.java:2866)
    at java.lang.Class.getMethod(Class.java:1676)
    at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: backtype.hadoop.pail.PailStructure
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 6 more
```

Not sure what else to try here - but will keep digging.

If someone can shed a light on this matter, it will be greatly appreciated.
